openapi: 3.0.0
info:
  title: Simple E-commerce API
  description: A simple API for managing products, orders, users, and categories in an e-commerce system.
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get all products
      description: Get a list of all products available.
      responses:
        '200':
          description: Get all products successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1products/get/responses/200/content/application~1json/schema'
    post:
      summary: Creat a new product
      description: Creat a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1products/get/responses/200/content/application~1json/schema'
      responses:
        '201':
          description: Creat new product successful
          content:
            application/json:
              schema:
                $ref: '#/paths/~1products/get/responses/200/content/application~1json/schema'