openapi: 3.0.0
servers:
  - description: SwaggerHub API
    url: HTTP
  - description: SwaggerHub Secure API
    url: HTTPS
info:
  title: A simple E-commerce API
  description: A simple API for managing products, orders, users, and categories in an e-commerce system.
  version: 1.0.0
paths:
  /products:
    get:
      summary: get all products
      description: get all available products.
      responses:
        '200':
          description: get all products successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/paths/~1products/get/responses/200/content/application~1json/schema'
    post:
      summary: create a new product
      description: create a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: create new product successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /products/productId:
    put:
      summary: update a product
      description: delete a product by the product id
      parameters:
        - name: productId
          required: true
          in: path
          description: id of the product
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: the product with that product id is updated successfully

    delete:
      summary: delete the product by the product id
      description: delete the product by the product id
      parameters:
        - name: productId
          required: true
          in: path
          description: id of the product
          schema:
            type: string
      responses:
        '204':
          description: the product with that product id is deleted successfully

  # /users:
  # /users/userId:

components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: string
          example: "102"
        title:
          type: string
          example: 'product1'
        price:
         type: integer
         example: 1
        description:
          type: string
          example: 'this is a product'
        size:
          type: number
          example: '40'
        images:
          type: string
          example: 'https://fastly.picsum.photos/id/5/640/480.jpg'
        categoryId:
          type: string

    User:
      type: object
      properties:
        userId:
          type: string
          example: '203'
        email:
          type: string
          example: 'user@mail.com'
        password:
          type: string
          example: 'password'
        fullname:
          type: string
          example: 'John Smith'
        role:
          type: string
          example: 'customer'
        avatar:
          type: string
          example: 'https://fastly.picsum.photos/id/5/640/480.jpg'
